# Generated by Django 5.0.3 on 2024-03-22 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_options_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новину', 'verbose_name_plural': 'Новини'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Користувача', 'verbose_name_plural': 'Користувачі'},
        ),
    ]
