# Generated by Django 5.0.3 on 2024-03-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_news_options_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='byte_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
