# Generated by Django 5.0.3 on 2024-04-25 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_base_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='byte_content',
            new_name='html_content',
        ),
    ]
