# Generated by Django 5.0.3 on 2024-04-26 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_byte_content_news_html_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='byte_content',
        ),
    ]
