# Generated by Django 5.0.3 on 2024-04-29 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_content_news_byte_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('N', 'Новина'), ('P', 'Параграф'), ('H', 'Заголовок'), ('PH', 'Фотографія')], max_length=2)),
                ('content', models.TextField()),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='main.news')),
            ],
        ),
    ]
