# Generated by Django 5.0.3 on 2024-04-29 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_contentblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.base'),
        ),
        migrations.DeleteModel(
            name='ContentBlock',
        ),
    ]
