# Generated by Django 5.0.3 on 2024-04-30 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_news_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
