# Generated by Django 5.0.3 on 2024-05-15 15:59

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_comment_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to=main.models.user_avatar_path),
        ),
    ]
