# Generated by Django 5.0.3 on 2024-05-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_comment_disliked_by_remove_comment_liked_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='disliked_by',
            field=models.ManyToManyField(related_name='disliked_comments', to='main.base'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_comments', to='main.base'),
        ),
    ]
