# Generated by Django 5.0.3 on 2024-05-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_comment_disliked_by_alter_comment_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='disliked_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='comment',
            name='disliked_by',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='comment',
            name='liked_by',
            field=models.JSONField(default=list),
        ),
    ]
