# Generated by Django 5.0.3 on 2024-05-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_comment_disliked_by_comment_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='disliked_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='comment',
            name='disliked_by',
            field=models.ManyToManyField(related_name='disliked_comments', to='main.base'),
        ),
        migrations.AddField(
            model_name='comment',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_comments', to='main.base'),
        ),
    ]
