# Generated by Django 5.0.3 on 2024-05-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_news_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
    ]
