# Generated by Django 5.0.3 on 2024-05-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='photo_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
