# Generated by Django 5.0.3 on 2024-05-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_remove_news_photo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='photo_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
