# Generated by Django 5.0.3 on 2024-05-16 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_news_photo_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='photo_path',
        ),
    ]
