# Generated by Django 5.0.3 on 2024-05-16 22:33

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_remove_news_image_newsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='1', upload_to=main.models.news_image_path),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='NewsImage',
        ),
    ]
