# Generated by Django 5.0.3 on 2024-05-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_news_image_delete_newsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
